name: Release
on:
  push:
    tags:
      - '*'
    branches: # TODO: Remove before merging.
      - fix-ci  # Pushing the feature branch should test this PR.
jobs:
  build:
    name: Build for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            name: linux64
            artifact_name: target/x86_64-unknown-linux-musl/release/mops-cli
            asset_name: mops-cli-linux64
          - os: macos-12
            name: macos
            artifact_name: target/release/mops-cli
            asset_name: mops-cli-macos
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Install stable toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build
        if: matrix.name == 'linux64'
        run: |
          docker run --rm -t \
            -v $HOME/.cargo/registry/:/root/.cargo/registry \
            -v "$(pwd)":/volume \
            clux/muslrust:stable \
            cargo build --release --locked --target x86_64-unknown-linux-musl
      - name: Build
        if: matrix.name == 'macos'
        run: cargo build --release --locked
      - name: 'Upload assets'
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3.2.1
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.artifact_name }}
          retention-days: 3
  test:
    needs: build
    name: Test for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            asset_name: mops-cli-linux64
          - os: ubuntu-20.04
            asset_name: mops-cli-linux64
          - os: macos-13
            asset_name: mops-cli-macos
          - os: macos-12
            asset_name: mops-cli-macos
    steps:
      - name: Get executable
        id: download
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: ${{ matrix.asset_name }}
      - name: Executable runs
        run: |
          chmod +x mops-cli
          ./mops-cli --help
  publish:
    needs: test
    name: Publish ${{ matrix.asset_name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - asset_name: mops-cli-linux64
          - asset_name: mops-cli-macos
    runs-on: ubuntu-latest
    steps:
      - name: Get executable
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: ${{ matrix.asset_name }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: mops-cli
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
